export const ahurareviews = [
  "The chicken puff was fresh, flaky, and full of flavour. A lovely bakery snack.",
  "Really enjoyed the mutton keema petis. The filling was tasty and nicely seasoned.",
  "Chicken tandoori roll was satisfying and packed with flavour. Would try it again.",
  "Chicken puff ka taste mast tha, pastry bhi crispy thi. Ek baar try karna banta hai.",
  "The Shrewsbury biscuit has such a nice buttery taste. Perfect with evening tea.",
  "Caramel custard was smooth and delicious. A lovely dessert after a quick snack.",
  "Mava cake was soft, rich, and had a lovely traditional bakery taste.",
  "Chicken cutlet was crispy outside and tasty inside. Good option for a quick bite.",
  "The chicken farcha was really enjoyable. Nice flavour and a satisfying portion.",
  "Loved the chicken pizza. The topping and bakery-style base worked really well.",

  "Caramel pudding was creamy and enjoyable. Definitely worth trying for dessert.",
  "The chicken puff was flaky and delicious. One of the items I would happily order again.",
  "Mutton keema petis had a delicious filling and a nice pastry texture.",
  "Chicken tandoori roll ka flavour ekdum zabardast tha. Achha filling wala snack hai.",
  "The tandoori roll was full of flavour and made for a filling snack.",
  "Shrewsbury biscuit was buttery, crumbly, and went perfectly with chai.",
  "The caramel custard had a lovely texture and wasn't too heavy.",
  "Really liked the mava cake. It had that classic bakery sweetness.",
  "Chicken cutlet was crispy, flavourful, and nicely prepared.",
  "The chicken farcha was a tasty change from regular bakery snacks.",

  "Chicken pizza was satisfying and had a nice combination of flavours.",
  "Caramel pudding was smooth and delicious. A nice sweet treat.",
  "Fresh chicken puff and a cup of tea make a great combination here.",
  "The keema petis was flavourful and had a good pastry-to-filling balance.",
  "Mutton keema petis ka filling bahut tasty tha. Chai ke saath perfect combination.",
  "Chicken tandoori roll was tasty and filling. Good for a quick lunch.",
  "The Shrewsbury biscuit reminded me of classic bakery treats from childhood.",
  "Caramel custard was creamy, smooth, and nicely sweet.",
  "Mava cake had a soft texture and a rich flavour. Enjoyed every bite.",
  "Chicken cutlet was nicely crispy and had good seasoning.",

  "Chicken farcha was delicious and had a satisfying crunchy coating.",
  "The chicken pizza was a nice choice for a quick evening snack.",
  "Really enjoyed the caramel pudding. Simple, tasty, and comforting.",
  "The chicken puff was one of my favourite things from the bakery visit.",
  "Mutton keema petis had a delicious filling and a lovely pastry texture.",
  "The tandoori roll was spicy enough and full of flavour. Very satisfying.",
  "Shrewsbury biscuit was buttery and crumbly in the best way.",
  "Caramel custard was a lovely dessert with a smooth, creamy texture.",
  "Mava cake was soft and had a nice traditional taste.",
  "The chicken cutlet was crispy and flavourful. A good snack option.",

  "Chicken farcha was tasty and nicely coated. Enjoyed the texture.",
  "Chicken pizza was flavourful and made for a satisfying snack.",
  "The caramel pudding was delicious and had a nice creamy consistency.",
  "Chicken puff was flaky, savoury, and perfect for a quick bakery stop.",
  "The mutton keema petis was tasty and had a generous-feeling filling.",
  "Chicken tandoori roll was delicious and packed with a lovely smoky flavour.",
  "The Shrewsbury biscuit was a simple but really enjoyable tea-time snack.",
  "Caramel custard had a smooth texture and a pleasant sweetness.",
  "Mava cake was rich, soft, and very enjoyable with tea.",
  "Chicken cutlet was crispy on the outside and flavourful inside.",

  "The chicken farcha was a tasty bakery-style chicken snack.",
  "Chicken pizza was enjoyable and had a nice cheesy flavour.",
  "Caramel pudding was smooth and sweet. A good dessert choice.",
  "The chicken puff was delicious and made a great evening snack.",
  "Mutton keema petis had a tasty filling with a nice flaky exterior.",
  "Really liked the chicken tandoori roll. It was filling and full of flavour.",
  "Shrewsbury biscuit was buttery and had a lovely melt-in-the-mouth texture.",
  "The caramel custard was creamy and nicely balanced in sweetness.",
  "Mava cake was soft, rich, and had a pleasant traditional bakery flavour.",
  "Chicken cutlet was a tasty choice for a quick snack.",

  "Chicken farcha had a nice crispy coating and delicious chicken flavour.",
  "The chicken pizza was satisfying and enjoyable.",
  "Caramel pudding was creamy, delicious, and a nice way to finish the meal.",
  "Loved the flaky texture of the chicken puff. Very enjoyable.",
  "The mutton keema petis was flavourful and nicely prepared.",
  "Chicken tandoori roll was tasty and filling. A good snack for hungry evenings.",
  "Shrewsbury biscuit had a lovely buttery taste and crumbly texture.",
  "The caramel custard was smooth and delicious. A nice sweet treat.",
  "Mava cake was soft and rich with a lovely bakery aroma.",
  "Chicken cutlet was crispy, tasty, and satisfying.",

  "Chicken farcha was really enjoyable and had a nice crunchy texture.",
  "The chicken pizza was flavourful and a good option for a quick bite.",
  "Caramel pudding was smooth and creamy. Enjoyed the dessert.",
  "The chicken puff was fresh-tasting and had a delicious savoury filling.",
  "Mutton keema petis was a great choice for a filling bakery snack.",
  "The tandoori roll was packed with flavour and had a nice texture.",
  "Shrewsbury biscuit was buttery, crumbly, and perfect with tea.",
  "Caramel custard was creamy and had a lovely smooth finish.",
  "Mava cake was delicious and had a nice rich flavour.",
  "Chicken cutlet was crispy and nicely seasoned.",

  "The chicken farcha was tasty and had a satisfying coating.",
  "Chicken pizza was enjoyable and had a good bakery-style taste.",
  "Caramel pudding was creamy, sweet, and delicious.",
  "Chicken puff ka taste mast tha, pastry bhi crispy thi. Ek baar try karna banta hai.",
  "Mutton keema petis mein filling kaafi flavourful thi. Ek aur lene ka mann karega.",
  "Chicken tandoori roll filling aur tasty tha. Evening snack ke liye sahi choice.",
  "Shrewsbury biscuit ka taste simple but delicious tha. Old-school bakery vibes aati hain.",
  "Caramel custard ka texture bahut smooth tha. Sweet craving ke liye accha option.",
  "Mava cake ka flavour rich aur texture soft tha. Chai ke saath bahut accha laga.",
  "Chicken cutlet ka crispy outside aur tasty inside combination accha tha.",

  "Chicken farcha try kiya aur kaafi enjoy kiya. Crunchy coating mast thi.",
  "Chicken pizza filling aur flavourful tha. Bakery-style pizza ka taste pasand aaya.",
  "Caramel pudding ka taste creamy aur balanced tha. Dessert mein acchi choice hai.",
  "Ahura Bakery ka chicken puff try kiya, kaafi tasty laga. Pastry ka texture bhi accha tha.",
  "Caramel custard smooth aur creamy tha. Sweet dish lovers ko pasand aayega.",
  "Mava cake soft tha aur traditional bakery wala taste aaya. Definitely try karna.",
  "Chicken cutlet crispy aur tasty tha. Quick snack ke liye achha option hai.",
  "Chicken farcha ka crispy coating aur chicken flavour dono acche lage.",
  "Chicken pizza ka taste accha tha, cheese aur toppings ka combination mast tha.",
  "Caramel pudding creamy aur delicious thi. Meal ke baad dessert ke liye perfect.",
];
