// export const reviews4Star: string[] = [
//   "Really good healthy food and a nice cozy vibe. A great cafe in Andheri to hang out with friends.",
//   "The protein bowls are very fresh and tasty. Service was slightly slow today, but the food quality makes up for it.",
//   "Nice place for a healthy breakfast. The cold coffee is really good and the seating is quite comfortable.",
//   "Tried their avocado toast and it was delicious. The cafe has a very peaceful environment to sit and work.",
//   "Good quality ingredients and the taste is very natural. One of the better healthy cafes I have tried around here.",
//   "A solid spot for fitness lovers looking for clean food. The menu has plenty of good low-calorie options.",
//   "The portion sizes are decent and the prices are reasonable. Very clean and hygienic place to eat.",
//   "I really liked their fresh fruit smoothies and sandwiches. Will definitely visit again when I am in the area.",
//   "Food tastes great and feels very light on the stomach. The sugar-free options on the menu are a nice touch.",
//   "Good place for a quick post-workout meal. The chicken salad was fresh, though I wish the portion was a bit bigger.",
// ];

// export const reviews5Star: string[] = [
//   "Absolutely love the healthy food options here in Andheri. The ambiance is super chill and the staff is very polite.",
//   "Best cafe for guilt-free eating! The cold coffee and protein bowls are super fresh and tasty. Highly recommend it.",
//   "Found my new favorite spot for a quick healthy breakfast. The vibe is amazing and the service is really fast.",
//   "This place serves the best avocado toast in town. Such a peaceful cafe to work from with great Wi-Fi.",
//   "Really impressed with the quality of fresh ingredients they use. Definitely the best healthy cafe I have visited recently.",
//   "A hidden gem for fitness lovers! The food is packed with flavor and doesn't compromise on the health aspect at all.",
//   "Great portion sizes and completely worth the price. The seating area is very clean and gives off a relaxing vibe.",
//   "I visit this cafe almost every weekend for their smoothies. The taste is consistently good and the staff is friendly!",
//   "Such a great dining experience with proper hygienic food preparation. The sugar-free desserts are a must-try here.",
//   "Perfect spot to grab a post-workout meal. The grilled chicken salad was incredibly fresh and filling.",
// ]
// ;

 export const aliqrareview: string[] = [
  "Best place in Jogeshwari West to buy authentic Pakistani lawn suits. The digital prints and lawn fabric quality are super comfortable for daily wear.",
  "Maine yahan se unstitched cotton suits liye the summer ke liye, color bilkul nahi gaya. Al Iqra Ladies Dress Jogeshwari ki one of the best shops hai.",
  "Got a gorgeous sharara set for my sister's nikah from Al Iqra. The hand-stitched detailing and fine threads look exceptionally rich.",
  "Al Iqra Ladies Dress in Jogeshwari West has an amazing range of everyday cotton materials as well as heavy party wear.",
  "Bohot pyara collection hai yahan casual suit materials ka. Jogeshwari me agar saste aur ache kapde chahiye toh yeh shop visit karo.",
  "Bought a semi-stitched Pakistani suit for an office event. The fitting adjustments were easy, and the fabric feels premium without being too heavy.",
  "The organza dupattas paired with their party wear suits add an amazing royal touch. Truly a great boutique in Jogeshwari West.",
  "Shadi ki shopping ke liye humne Al Iqra explore kiya tha, aur inka bridal aur festive range sach me bohot unique hai.",
  "Simple printed lawn suits se lekar heavy wedding outfits till sab mil jata hai yahan. Jogeshwari me yeh sabse reliable dress shop hai.",
  "The customer service is great; the staff helped me match a contrast dupatta with my unstitched suit material perfectly.",
  "Jogeshwari West me Al Iqra jaisa variety kisi aur shop par nahi milta. Daily wear cotton suits ho ya festive wear, sabka quality solid hai.",
  "Maine apni mom ke liye daily wear suits liye the yahan se, fabric itna soft hai ki woh hamesha yahin se leti hain ab.",
  "The intricate threadwork on my cousin's reception gown was stunning. Highly recommend Al Iqra for anyone shopping around Jogeshwari.",
  "Aisi dukaan Jogeshwari me milna mushkil hai jahan budget me itne acche designer suits mil jayein.",
  "Bought unstitched lawn suits for summer. The breathable fabric and lively colors make them absolute favorites.",
  "Al Iqra Ladies Dress is my go-to store near Patel Estate, Jogeshwari. Their readymade kurti and suit sets are very stylish.",
  "Nikah outfit ke liye heavy garara chahiye tha, aur inke paas jo collection tha woh dekh kar turant pasand aa gaya.",
  "Pure Jogeshwari West me inka dress material collection sabse updated rehta hai. Naye designs hamesha milte hain.",
  "Friendly shopkeepers and honest pricing. Bought two casual suits and one heavy party wear piece without any hassle.",
  "The fabric durability of their cotton lawn suits is amazing. Even after multiple washes, the texture remains intact.",
  "Jogeshwari me agar kisi ko traditional Pakistani suits chahiye toh Al Iqra hi sabse pehla option hona chahiye.",
  "Maine ek simple embroidered suit liya tha college function ke liye, sabne pucha kahan se liya itna accha piece.",
  "The custom tailoring and fitting assistance at Al Iqra Dress Shop made my festive shopping completely stress-free.",
  "Bohot hi acchi variety hai unstitched suits ki. Jogeshwari West ke local market me yeh shop sabse alag hai.",
  "Got a stunning velvet touch suit for winter weddings. The warmth and rich look of the fabric are top-tier.",
  "Al Iqra in Jogeshwari offers an excellent blend of traditional and modern ethnic fashion for women.",
  "Daily wear ke liye breathable cotton suits chahiye ho toh yahan zarur aana chahiye. Bohot wide range hai.",
  "The dupatta collections with heavy borders completely transform a simple suit into a party-ready outfit.",
  "Jogeshwari West mein ladies dresses ke liye Al Iqra sabse trusted name ban chuka hai mere family me.",
  "Unstitched lawn suits ki quality itni acchi hai ki stitching ke baad designer piece lagta hai.",
  "Found a brilliant pastel-colored Pakistani suit set for a day function. The fabric drape is gorgeous.",
  "Shadi ke trousseau ke liye kaafi saare suits yahin se liye the. Quality consistent rahi hai har ek piece me.",
  "Jogeshwari me itne reasonable rates par itna accha party wear milna badi baat hai.",
  "The stitching neatness on their readymade suits is brilliant. No loose threads or bad finishes.",
  "Al Iqra Ladies Dress near Jogeshwari station area is very accessible and has an incredible stock.",
  "Casual cotton prints yahan bohot hi vibrant milte hain. Summer shopping ke liye perfect destination hai.",
  "Heavy festive suits par jo handwork hota hai, woh ekdum neat aur clean hota hai.",
  "Jogeshwari West ke sabse behtareen boutiques me se ek hai yeh. Service bhi bahut fast aur achi hai.",
  "Maine online bhi try kiya tha par Al Iqra ke store par jo fabric touch karke lene ka maza hai woh alag hai.",
  "The variety of unstitched dress materials for everyday office wear is impressive and very pocket-friendly.",
  "Eid shopping ke liye humesha Al Iqra hi aate hain kyunki naye trends sabse pehle yahin aate hain.",
  "Jogeshwari me ladies garments ke liye yeh shop ek hidden gem hai jahan sab kuch milta hai.",
  "The color fastness of their cotton suits is great. No bleeding or fading after washing.",
  "Got a gorgeous gharara piece for a family function with flawless custom fitting support.",
  "Al Iqra Ladies Dress Jogeshwari has maintained top-notch quality standards over the years.",
  "Simple lawn suits se lekar grand reception dresses tak sab kuch ek hi roof ke niche mil jata hai.",
  "The staff is cooperative and doesn't rush you while you are selecting clothes for hours.",
  "Jogeshwari West me agar koi achi dress shop dhund raha hai toh main hamesha Al Iqra recommend karta hoon.",
  "The printed lawn suits feel extremely light and airy, making them ideal for daily household work or casual outings.",
  "Purchased a heavy party wear suit with mirror work accents; it looked extremely grand under the lights.",
  "Al Iqra ka unstitched suit material durable bhi hai aur budget me bhi fit baithta hai.",
  "Jogeshwari ki is boutique ne mere saare festive wardrobe requirements ko ek baar me solve kar diya.",
  "The organza and chiffon dupattas add a touch of elegance that makes any basic suit look high-end.",
  "Maine apne friends ko bhi yahan suggest kiya hai unstitched Pakistani suits ke liye.",
  "Jogeshwari West mein itna bada variety aur stock kisi aur local store par nahi dekha maine.",
  "The fabric quality and stitching finish of their readymade daily wear items are exceptionally reliable.",
  "Al Iqra Ladies Dress provides amazing value for money whether you buy casual or luxury festive wear.",
  "Bohot hi pyara experience raha shopping ka. Staff ne sabhi suits ache se dikhaye aur rate bhi fair the.",
  "Jogeshwari me sabse best ethnic wear destination hai yeh, especially Pakistani lawn aur party suits ke liye.",
  "Five stars for Al Iqra Ladies Dress! Great variety, local accessibility in Jogeshwari West, and top quality.",
];
